# -*- coding: utf-8 -*-
"""Jogo premiado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ly-EectYZJn3aJ8a30Y29V3iyHm_Ni_O
"""

def jogo_premiado(a,b):
  if (a+b == 7 or a+b == 11):
    return 'Premiado!'
  return nova_jogada(a,b)

def nova_jogada(a,b):
  soma = a + b
  if (soma == 12):
    return 'Premiado!'
  return 'Tente novamente :('

import random
a = random.randint(1,11)
b = random.randint(1,11)
jogo_premiado(a,b)